### ISSUE TITLE
langer Datensatz mit Lücken

### ISSUE THREAD

**Issue by kzwintz** [muma7490/SMURFS#2]
Hallo Marco,
Ich hab den Test wiederholt: vier Lichtkurven aufgenommen in 2004, 2006, 2011 und 2017. SMURFS macht nichts, sondern schreibt (brav):
"Ignoring time base from 0 to 6585 because the gap Ratio is greater 0.5. Gap Ratio is 0.9817461560352049"
Ich denke, es sollte nur abbrechen, wenn subsets verlangt werden, nicht aber wenn ich eine Frequenzanalyse haben will. Oder ich muss eine Möglichkeit haben, das Programm zu zwingen trotz Gaps zu rechnen.
LG, Konstanze

**Comment by muma7490** [comment]
Fixed.
