### ISSUE TITLE
surfs läuft nicht von überall

### ISSUE THREAD

**Issue by kzwintz** [muma7490/SMURFS#3]
Hi Marco,
Ich habe deine Anleitung auf GitHub befolgt und smurfs neu installiert. Danach funktioniert der Befehl "python -m smurfs <filename>" aus einem anderen directory nicht, sollte er aber laut Deiner Anleitung. In dem Installationsverzeichnis funktioniert es normal.
Ich schätze mal irgendein Pfad muss noch in der Shell gesetzt werden?
Schau Dir das bitte an. Danke! LG, Konstanze

**Comment by muma7490** [comment]
Notiz: SMURFS funktioniert richtig, Problem ist Anleitung. Verfeinerung der Anleitung ist notwendig.
